accounts/urls.py
from django.urls import path

from .views import (
    LogInView, ResendActivationCodeView, RemindUsernameView, SignUpView, ActivateView, LogOutView,
    ChangeEmailView, ChangeEmailActivateView, ChangeProfileView, ChangePasswordView,
    RestorePasswordView, RestorePasswordDoneView, RestorePasswordConfirmView, LogOutConfirmView,
)

app_name = 'accounts'

urlpatterns = [
    path('log-in/', LogInView.as_view(), name='log_in'),
    path('log-out/confirm/', LogOutConfirmView.as_view(), name='log_out_confirm'),
    path('log-out/', LogOutView.as_view(), name='log_out'),

    path('resend/activation-code/', ResendActivationCodeView.as_view(), name='resend_activation_code'),

    path('sign-up/', SignUpView.as_view(), name='sign_up'),
    path('activate/<code>/', ActivateView.as_view(), name='activate'),

    path('restore/password/', RestorePasswordView.as_view(), name='restore_password'),
    path('restore/password/done/', RestorePasswordDoneView.as_view(), name='restore_password_done'),
    path('restore/<uidb64>/<token>/', RestorePasswordConfirmView.as_view(), name='restore_password_confirm'),

    path('remind/username/', RemindUsernameView.as_view(), name='remind_username'),

    path('change/profile/', ChangeProfileView.as_view(), name='change_profile'),
    path('change/password/', ChangePasswordView.as_view(), name='change_password'),
    path('change/email/', ChangeEmailView.as_view(), name='change_email'),
    path('change/email/<code>/', ChangeEmailActivateView.as_view(), name='change_email_activation'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('velocipede.urls', 'velocipede')),
    path('accounts/', include('accounts.urls', 'accounts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

velocipede/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import HomepageView, RentListView, RentedView
app_name = 'velocipede'
urlpatterns = [
  path('', HomepageView.as_view(), name="homepage"),
  path('rent', RentListView.as_view(), name="rentlist"),
  path('rented', login_required(RentedView.as_view()), name="rented"),
]

velocipede/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone

User = settings.AUTH_USER_MODEL

# Create your models here.
class Velocipede(models.Model):
  thumbnail = models.ImageField(upload_to="velocipede/images/thumbnails", height_field="thumbnail_height", width_field="thumbnail_width", max_length=None, blank=True)
  thumbnail_height = models.IntegerField(default=1280, editable=False)
  thumbnail_width = models.IntegerField(default=720, editable=False)
  cost = models.PositiveIntegerField()
  in_use = models.BooleanField()
  current_station = models.ForeignKey('Station', on_delete=models.SET_NULL, null=True, blank=True)
    
  def __str__(self):
      return f"Velocipede (ID: {self.id})"

class Station(models.Model):
    name = models.CharField(max_length=255)
    location = models.CharField(max_length=255)
    
    def __str__(self):
        return self.name

class Rent(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    velocipede = models.ForeignKey(Velocipede, on_delete=models.CASCADE)
    start_time = models.DateTimeField(default=timezone.now)
    end_time = models.DateTimeField(null=True, blank=True)
    start_station = models.ForeignKey(Station, related_name='rent_start_station', on_delete=models.SET_NULL, null=True)
    end_station = models.ForeignKey(Station, related_name='rent_end_station', on_delete=models.SET_NULL, null=True, blank=True)
    
    def __str__(self):
        return f"Rent {self.id} by {self.user.first_name, self.user.last_name}"

class Payment(models.Model):
    rent = models.OneToOneField(Rent, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    payment_date = models.DateTimeField(default=timezone.now)
    
    def __str__(self):
        return f"Payment {self.id} for Rent {self.rent_id}"

velocipede/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.views.generic import TemplateView, ListView
from django.views.generic.base import ContextMixin
from django.conf import settings
from .models import Velocipede, Rent


# Create your views here.
class HomepageView(TemplateView, ContextMixin):
  template_name = "velocipede/homepage.html"
  extra_context = {
    "thumbnails": Velocipede.objects.all()[:3],
    "active": 'home',
  }

class RentedView(TemplateView, ListView, ContextMixin):
  extra_context = {
    "active": 'rented'
  }
  template_name = "velocipede/rented.html"
  model = Rent
  object_list = Rent.objects.all()
  context_object_name = "rents"
  paginate_by = 36

  def get_queryset(self) -> QuerySet[any]:

    q = super().get_queryset()
    return q.filter(user_id=self. request.user_id)

class RentListView(TemplateView, ListView, ContextMixin):
  extra_context = {
    "active": 'to_rent'
  }
  template_name = "velocipede/rentlist.html"
  model = Velocipede
  object_list = Velocipede.objects.filter(in_use=False)
  context_object_name = "velocipedes"
  paginate_by = 36

velocipede/templates/velocipede/footer.html
{% load static %}
<footer class="d-flex flex-wrap justify-content-between align-items-center pt-3 my-4 border-top">
  <div class="col-md-4 d-flex align-items-center justify-content-center">
    <a href="{% url 'velocipede:homepage' %}" class="mb-3 me-2 mb-md-0 text-body-secondary text-decoration-none lh-1">
      <img src="{% static 'velocipede/images/icons/main_icon_dark.png' %}" class="bi d-block mx-auto mb-1">
    </a>
    <span class="mb-3 mb-md-0 text-body-secondary">© 2024 Company, Inc</span>
  </div>

  <ul class="nav col-md-4 justify-content-center list-unstyled d-flex">
    <li class="ms-3"><a class="text-body-secondary" href="#"><img class="bi" width="40" height="40" src="{% static 'velocipede/images/icons/x.png' %}" alt="X socials"></a></li>
    <li class="ms-3"><a class="text-body-secondary" href="#"><img class="bi" width="40" height="40" src="{% static 'velocipede/images/icons/instagram.png' %}" alt="Instagram socials"></a></li>
  </ul>
</footer>

velocipede/templates/velocipede/header.html
{% load static %}
<header class="header px-3 py-2 text-bg-dark border-bottom">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <a href="{% url 'velocipede:homepage' %}" class="d-flex align-items-center my-2 my-lg-0 me-lg-auto text-white text-decoration-none">
        <img src="{% static 'velocipede/images/icons/main_icon.png' %}" class="bi d-block mx-auto mb-1">
      </a>

      <ul class="nav col-12 col-lg-auto my-2 justify-content-center my-md-0 text-small">
        <li>
          <a href="{% url 'velocipede:homepage' %}" class="nav-link {% if active == 'home' %}text-secondary{% else %}text-white{% endif %}">
            <img src="{% static 'velocipede/images/icons/home.png' %}" class="bi d-block mx-auto mb-1" width="24" height="24">
            Home
          </a>
        </li>
        <li>
          <a href="{% url 'velocipede:rented' %}" class="nav-link {% if active == 'rented' %}text-secondary{% else %}text-white{% endif %}">
            <img src="{% static 'velocipede/images/icons/rented.png' %}" class="bi d-block mx-auto mb-1" width="24" height="24">
            Rented
          </a>
        </li>
        <li>
          <a href="{% url 'velocipede:rentlist' %}" class="nav-link {% if active == 'to_rent' %}text-secondary{% else %}text-white{% endif %}">
            <img src="{% static 'velocipede/images/icons/velocipede.png' %}" class="bi d-block mx-auto mb-1" width="24" height="24">
            To Rent
          </a>
        </li>
        <li>
          <a href="{% if request.user.is_authenticated %}{% url 'accounts:log_out_confirm' %}{% else %}{% url 'accounts:log_in' %}{% endif %}" class="nav-link {% if active == 'customer' %}text-secondary{% else %}text-white{% endif %}">
            <img src="{% static 'velocipede/images/icons/user.png' %}" class="bi d-block mx-auto mb-1" width="24" height="24">
            Customer
          </a>
        </li>
      </ul>
    </div>
  </div>
</header>

velocipede/templates/velocipede/homepage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="shortcut icon" href="{% static 'velocipede/images/icons/favicon.ico' %}" type="image/x-icon">
  <link rel="stylesheet" href="{% static '/velocipede/styles/global.css' %}">
  <link rel="stylesheet" href="{% static '/velocipede/styles/homepage.css' %}">
  <link rel="stylesheet" href="{% static '/velocipede/styles/header.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <title>Оренда Велосипедів | Лютіков</title>
</head>
<body>
  <div class="global-container">
    {% include "./header.html" %}
    <main class="main main_homepage">
      <div id="velocipedeCarousel" class="carousel slide carousel-fade" data-bs-ride="carousel">
        <div class="carousel-inner">
          {% for thumbnail in thumbnails %}
          <div class="carousel-item {% if forloop.first %}active{% endif %}">
            <img src="{% get_media_prefix %}{{thumbnail.thumbnail}}" class="d-block">
            <div class="carousel-caption d-none d-md-block">
              <h5>The Bike</h5>
              <p>Fast and furious.</p>
              <button class="btn text-light bg-success bg-gradient py-1" type="button">Rent it now!</button>
            </div>      
          </div>
          {% endfor %}
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#velocipedeCarousel" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#velocipedeCarousel" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
        <div class="carousel-indicators position-relative">
          <button type="button" data-bs-target="#velocipedeCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
          <button type="button" data-bs-target="#velocipedeCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
          <button type="button" data-bs-target="#velocipedeCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>      
      </div>
      <div class="px-3 text-center w-50 m-auto">
        <h1>Rent With Ease!</h1>
        <p class="lead">You choose location, bike and how to pay, we do rest!</p>
        <p class="lead">
          <a href="{% url 'velocipede:rentlist' %}" class="btn btn-lg btn-light fw-bold border-black bg-white">Explore</a>
        </p>
      </div>
    </main>
    {% include "./footer.html" %}  
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  <script src="{% static 'velocipede/scripts/homepage.js' %}"></script>
</body>
</html>

velocipede/templates/velocipede/rented.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="shortcut icon" href="{% static 'velocipede/images/icons/favicon.ico' %}" type="image/x-icon">
  <link rel="stylesheet" href="{% static '/velocipede/styles/global.css' %}">
  <link rel="stylesheet" href="{% static '/velocipede/styles/rentlist.css' %}">
  <link rel="stylesheet" href="{% static '/velocipede/styles/header.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <title>Ваші Орендування | Лютіков</title>
</head>
<body>
  <div class="global-container">
    {% include "velocipede/header.html" %}
    <main class="main d-flex flex-column">
      <div class="card-container text-center row row-cols-1 row-cols-md-2 g-4 flex-grow-1">
        {% for r in rents %}
        <div class="col">
          <div class="card">
            <img src="{% get_media_prefix %}{{r.velocipede.thumbnail}}" class="card-img-top" alt="Velocipede for {{v.cost}}">
            <div class="card-body">
              <h5 class="card-title">{{r.velocipede.cost}}₴</h5>
              <p class="card-text">Rent time: {{r.start_time}}-{{r.end_time}}</p>
              <p class="card-text">Start station: {{r.start_station}}</p>
              <p class="card-text">End station: {{r.end_station}}</p>
            </div>
          </div>
        </div>
        {% empty %}
        <p class="w-100 my-auto text-center p-4 bg-light">No Rents Were Made</p>
        {% endfor %}
      </div>
      <div class="container d-flex justify-content-center mt-4">
        <div class="pagination-container">
          <nav aria-label="Page navigation">
            <ul class="pagination">

            </ul>
          </nav>
        </div>
      </div>
    </main>
    {% include "velocipede/footer.html" %}
  </div>
  {{paginator.num_pages|json_script:"totalPagesJSON"}}
  {{page_obj.number|json_script:"currentPageJSON"}}
  <script src="{% static 'velocipede/scripts/pagination.js' %}"></script>
</body>

</html>

velocipede/templates/velocipede/rentlist.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="shortcut icon" href="{% static 'velocipede/images/icons/favicon.ico' %}" type="image/x-icon">
  <link rel="stylesheet" href="{% static '/velocipede/styles/global.css' %}">
  <link rel="stylesheet" href="{% static '/velocipede/styles/rentlist.css' %}">
  <link rel="stylesheet" href="{% static '/velocipede/styles/header.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <title>Орендувати | Лютіков</title>
</head>

<body>
  <div class="global-container">
    {% include "velocipede/header.html" %}
    <main class="main d-flex flex-column">
      <div class="card-container text-center row row-cols-1 row-cols-md-2 g-4 flex-grow-1">
        {% for v in velocipedes %}
        <div class="col">
          <div class="card">
            <img src="{% get_media_prefix %}{{v.thumbnail}}" class="card-img-top" alt="Velocipede for {{v.cost}}">
            <div class="card-body">
              <h5 class="card-title">{{v.cost}}₴</h5>
              <p class="card-text"><button class="btn btn-primary btn-success w-100 h-100" type="button">Rent
                  Now</button></p>
            </div>
          </div>
        </div>
        {% empty %}
        <p class="w-100 my-auto text-center p-4 bg-light">No nentings are possible yet, excuse us until we finish our work.</p>
        <p class="w-100 my-auto text-center p-4 bg-light">Thanks For Your Patience!</p>
        {% endfor %}
      </div>
      <div class="container d-flex justify-content-center mt-4">
        <div class="pagination-container">
          <nav aria-label="Page navigation">
            <ul class="pagination">

            </ul>
          </nav>
        </div>
      </div>
    </main>
    {% include "velocipede/footer.html" %}
  </div>
  {{paginator.num_pages|json_script:"totalPagesJSON"}}
  {{page_obj.number|json_script:"currentPageJSON"}}
  <script src="{% static 'velocipede/scripts/pagination.js' %}"></script>
</body>

</html>